name: Notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - obspy=1.3.0
  - matplotlib
  - jupyter-book>=0.13
  - ipython
  - Pygments
  - pygmt
  - json5
  - faker
  - tqdm
  - retry
