# Learn more at https://jupyterbook.org/customize/config.html


#######################################################################################
# Book settings
title                       : Seismology Notebook  # The title of the book. Will be placed in the left navbar.
author                      : Fu Yin  # The author of the book
logo                        : logo.png
copyright                   : "2021â€“2022"   # Copyright year to be placed in the footer
exclude_patterns            : [_build, Thumbs.db, .DS_Store]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
only_build_toc_files        : false   # Auto-exclude files not in the toc


#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : 120    # The maximum time (in seconds) each notebook cell is allowed to run.
  allow_errors              : false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.


#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : xelatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  latex_documents: 
    targetname              : book.tex # Define the name of the latex output file for PDF builds


#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)

repository:
  url                       : https://github.com/Seismology101/Notebook  # Online location of your book
  path_to_book              : book  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)


#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context
  myst_substitutions:
    Fu: "[Fu Yin](https://yinfu.info/)"


#######################################################################################
# HTML-specific settings
html:
  favicon                   : logo.png # A path to a favicon image
  use_issues_button         : true # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true # Whether to add a link to your repository button
  use_multitoc_numbering    : true # Continuous numbering across parts/chapters
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  baseurl                   : "https://seismology101.github.io/Notebook/" # # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false
  announcement              : "Welcome ðŸ‘‹" # A banner announcement at the top of the site.


#######################################################################################
# Advanced sphinx settings
sphinx:
  config:                     # key-value pairs to directly over-ride the Sphinx configuration
    bibtex_default_style    : plain
    bibtex_reference_style  : author_year

# citation
bibtex_bibfiles:
  - references.bib
